
Les données présentées dans ce document ne concernent que les personnels et étudiants du Ministère de l'enseignement supérieure, de la recherche et de l'innovation.

### Les étudiantes et étudiants {-}

1,8 millions d'étudiants sont recensés, pour près de 3 millions d'étudiants en tout. 

- Pour la première fois depuis 15 ans, les effectifs étudiants sont en baisse, en raison notamment de la démographie, et peut-être également en raison d'une régulation post-COVID.
- __Entre 2013 et 2021, le nombre de ces étudiants à cru de 14%__, en particulier en premier cycle (+15%) et sauf en doctorat (-8%). 
- Dans le même temps, __les effectifs enseignants n'ont cru que de 4%, conduisant à une chute du taux d'encadrement pédagogique de -13%__. 
- Le nombre d'inscription en diplôme d'établissement (DE ou DU) a cru de +16%.

### Les personnels {-}

Les données recensent aussi près de 99 600 personnels d'enseignement et de recherche (E-EC) et près de 96 000 personnels BIATS. Entre 2015 et 2021 :

- __le taux de titularité de ces personnels a baissé de -4%__, particulièrement en raison des politiques RH des universités. 
- Le nombre d'enseignants titulaires continue sa baisse (-3%) et celui des personnels BIATSS titulaires la commence (-1%).
- Cette dynamique s'explique surtout par __un plus grand recours aux contractuels, particulièrement pour l'enseignement__ (+22% de doctorants et ATER, +26% d'E-EC contractuels, hors vacataires, entre 2013 et 2021).
- Cette contractualisation est encore plus marquée dans les universités (+27% et +39%).
- Parmi les personnels BIATSS, les effectifs de catégorie A et B augmentent (+26% et +13%), alors que ceux de C diminuent (-19%).

```{=latex}
\vfill\null
\columnbreak 
```

### Les finances {-}

Une partie de la dynamique des recrutements s'explique par les transformations du système de financement, dont les données montrent la ventilation de presque 18 Md€. Entre 2013 et 2021 :

- Les subventions pour charge de service public (SCSP) ont augmenté de +15% (+11% pour les universités), ce qui reste inférieur à l'augmentation du nombre d'étudiants et ne prend pas compte l'inflation.
- En revanche, __les recettes propres sont en pleine augmentation, atteignant 2,4Md€__, mais elles ne permettent légalement pas de rémunérer des fonctionnaires.
- Issues des droits d'inscription, de la formation continue, de l'apprentissage et de la VAE, __les recettes propres formation ont augmenté de +79%__ (+72% pour les universités).
- Issues des des appels à projets, contrats et prestations, __les recettes propres recherche ont plus que triplé avec +241%__ (+249% pour les universités).
- Dans le même temps, la masse salariale, qui représente le trois quart des dépenses, n'a cru que de 9% (8% dans les universités).

### Les universités {-}

Au sein des universités, les situations et dynamiques peuvent être très différentes.

- Les budgets par étudiant vont de 2,5k€ à 16k€, et des taux de SCSP de moins de 20% à plus de 95%.
- __Les recettes propres formation vont de 170€ à 2350€ par étudiant en moyenne, et celles recherche de 410€ à 81k€ par enseignant-chercheur en moyenne__. 
- On retrouve la même diversité pour les taux de titularité (de 49% à 77%), les taux d'encadrement pédagogique (de 2,1 à 6,6 enseignants pour 100 étudiants), ou encore les taux d'encadrement administratif (de 38% à 62% des personnels sont BIATSS).

Si l'on prend en compte les autres type d'établissements du MESRI, alors ces disparités sont encore plus importantes, exigeants des représentations exhaustives.