---
title: "Représentations mise en ligne pour les universités"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(kpiESR)
library(tidyverse)
library(ggcpesrthemes)
library(cowplot)

source("tdbesr-plots.R")
theme_cpesr_setup(authors = "Julien Gossa", source = "données SIES - https://cpesr.fr/tableau-de-bord-esr/")

etabs <- esr.etab %>% filter(Plotable, Groupe == "Universités et assimilés") 
```

```
  - twtexte:[#DataESR #LRU] Indicateurs de performances de l'#ESR.
  - twalt:@juliengossa LO 2.0 www.cpesr.fr
  - twurl:1597001250222280704
  - url:https://cpesr.fr/tableau-de-bord-esr/
``` 

```{r fun_serie, include=FALSE}
combine_plots_series_online <- function(plots, dim, etab, kpi) {
  plot_abs <- plots[[paste0(dim,".abs")]]
  plot_evol <- plots[[paste0(dim,".evol")]]
  plot_norm <- plots[[paste0(dim,".norm")]]
  
  title <- ggdraw() + 
    draw_label(paste(etab$Etablissement," : ",kpi,"en",rentrée), 
               fontface = 'bold', x = 0, hjust = 0, vjust = 0.5) +
    theme(plot.margin = margin(0, 0, 0, 7))

  expl <- ggdraw() + 
    draw_label("En haut : valeurs normalisées. Chaque point représente un établissement.\nLe violon montre leur distribution et les barres les valeurs d'ensemble.\nA gauche : évolution en valeurs 100.\nla zone grise représente la moitié des établissements.\nCes données peuvent contenir des erreurs.", 
               fontfamily = "Raleway", fontface = "italic",
               size = 7, x = 0, hjust = 0, vjust=0.4) +
    theme(plot.margin = margin(0, 0, 0, 2))

  legend <- get_legend(plot_evol + 
                   ggplot2::theme(legend.direction = "horizontal", 
                                  legend.position = "bottom", 
                                  legend.title=element_blank(),
                                  rect = element_rect(fill = "transparent")))

  
  
  plot_grid(ncol=1, rel_heights = c(1,7,0.5,0.5), title,
    plot_grid (nrow = 1, align = "hv", rel_widths = c(4,0.1,3.5),
               plot_grid(ncol = 1, rel_heights = c(3,2), # align="v", axis = "lr",
                         plot_abs + rm_xytext + rm_ymingrid + rm_xgrid + rm_facetmargins,
                         plot_evol + sats + rm_ygrid + rm_label + shrink_xtext + rle_margin + rm_ytextmargin + small_facetmargins),
               "",
               plot_grid(ncol = 1, rel_heights = c(7,1),
                         plot_norm + rm_lt  + rm_ymingrid + theme(panel.spacing = unit(0, "pt"), axis.text.y = element_text(size=rel(0.8))),
                         expl)
               ),
    legend,
     cowplot::get_plot_component(ggplot() + cpesr_cap(oneline = TRUE), pattern = "caption"))
}
```


```{r fun_kpi, include=FALSE}

combine_plots_kpi_online <- function(rentrée, etab, lfc, ilfc, style = kpiesr_style()) {
  
  sublfc = list(
    labels = lfc$labels[ilfc],
    factors = lfc$factors[ilfc],
    colors = lfc$colors[ilfc],
    desc = lfc$desc[ilfc],
    y_labels = lfc$y_labels
  )
  
  title <- ggdraw() + 
    draw_label(paste(etab$Etablissement," : ", sublfc$labels[[1]]), 
               fontface = 'bold', x = 0, hjust = 0, vjust = 0.5) +
    theme(plot.margin = margin(0, 0, 0, 7))

  expl <- ggdraw() + 
    draw_label(paste0(sublfc$desc[[1]], 
                      "\nA gauche : Evolution pluriannuelle. Attention : l'échelle ne commence pas à zéro.",
                      "\nA droite : Valeur en ",rentrée,". Chaque point représente un établissement.\nLe violon montre leur distribution. Les barres indiquent les valeurs ensemble et groupe.\nCes données peuvent contenir des erreurs."), 
               fontfamily = "Raleway", fontface = "italic",
               size = 9, x = 0, hjust = 0, vjust=0.5) +
    theme(plot.margin = margin(0, 0, 0, 10))

plot_line <- kpiesr_plot_line(id = etab$pid, vars = c(sublfc$factors[[1]]), groupe = "Universités et assimilés") +
  theme(axis.title.y = element_blank(), legend.position = "None")
plot_norm <- kpiesr_plot_norm_simple(rentrée, etab$pid, etab$Groupe, sublfc, style) +
  rm_lt + rl_margin + theme(strip.text = element_blank())
    
  legend <- get_legend(plot_line + 
                       guides(color = "none", alpha = "none") +
                       ggplot2::theme(legend.direction = "vertical", 
                                      legend.key.height = unit(0.7,"line"),
                                      legend.position = "bottom", 
                                      legend.title=element_blank(),
                                      rect = element_rect(fill = "transparent")))
  
  
  plot_grid(ncol=1, rel_heights = c(1,7,2,0.5), title,
    plot_grid(nrow = 1, rel_widths = c(5,1), plot_line, plot_norm),
    plot_grid(nrow = 1, rel_widths = c(3,1), expl, legend),
    cowplot::get_plot_component(ggplot() + cpesr_cap(oneline = TRUE), pattern = "caption")
    )
}

  #combine_plots_kpi_online(rentrée, etab, kpiesr_lfc$K, 1)


```


```{r loop, warning=FALSE, results='asis', cache = FALSE, eval=TRUE}
plotloop <- function(a,b) {
  for (i in seq(a,b)) {
    etab <- etabs[i,]
    
    cat("\n\n## ", etab$Etablissement," ", str_replace(etab$twitter,"https://twitter.com/","@"), "\n\n")
    
    #message("\nProcessing ",i,"/",nrow(etabs)," : ",strvar(etab$Etablissement), " ", etab$pid, " ", etab$UAI)
    plots <- kpiesr_plot_all(rentrée, etab$pid, etab$Groupe, style.k=k_style, style.o=o_style, style.o.norm = onorm_style, experimental = TRUE)
  
    #print(combine_plots_groupe(plots))
    #print(combine_plots_series(plots))
  
    for(ilfc in seq(1,length(kpiesr_lfc$K$factors))) {
      print(combine_plots_kpi_online(rentrée, etab, kpiesr_lfc$K, ilfc, k_style))
      cat("\n\n")
    }
  
    print(combine_plots_series_online(plots, "etu", etab, "Etudiants"))
    cat("\n\n")
    print(combine_plots_series_online(plots, "bia", etab, "BIATSS"))
    cat("\n\n")
    print(combine_plots_series_online(plots, "ens", etab, "Enseignants"))
    cat("\n\n")
    print(combine_plots_series_online(plots, "fin", etab, "Finances"))
    cat("\n\n")
    print(combine_plots_series_online(plots, "imo", etab, "Immobiliers"))
    cat("\n\n")
  
    gc()
  }
}
```



```{r univ_a, warning=FALSE, results='asis', cache = FALSE, eval=TRUE}
plotloop(1,20)
```

```{r univ_b, warning=FALSE, results='asis', cache = FALSE, eval=TRUE}
plotloop(21,40)
```

```{r univ_c, warning=FALSE, results='asis', cache = FALSE, eval=TRUE}
plotloop(41,60)
```

```{r univ_d, warning=FALSE, results='asis', cache = FALSE, eval=TRUE}
plotloop(61,nrow(etabs))
```
